menu:
  Articles: /
  Dev Log: /dev-log/

google_analytics_id: UA-66600710-1

github_id: bengsfort
twitter_id: bengsfort
fb_admins: 100000177595822
fb_app_id: 1893256420958255

author:
  name: Matt Bengston
  avatar: /images/avatar.png
  position: Software Developer
  employer: Unity Technologies
  employer_uri: https://unity3d.com
  